/* Library domain: Content Cards, night/food/shopping/photos/culture/favorites and their filters. */
(() => {
  'use strict';
  function create(config){
    const {$,tripData,items,esc,photoSystem,travelUtils,favoritesStore,navigation,dateRail,markRendered,setSharedDay,getJourney,getReader,showView}=config;
    const {category,stars,hotelDistanceCardValue}=travelUtils;
    let nightDay='all',foodCity='all',cultureFilter='all',photoFilter='all';
    const saveButton=p=>`<button class="save-btn" data-save="${esc(p.id)}" aria-pressed="${favoritesStore.has(p.id)}" aria-label="${favoritesStore.has(p.id)?'取消收藏':'收藏'}${esc(p.name)}">${favoritesStore.has(p.id)?'♥':'♡'}</button>`;
    const variant=p=>p.type==='night'?'night':p.type==='food'?'food':p.type==='shopping'?'shopping':p.type==='photo'?'photo':'place';
    const cell=(label,value)=>`<div class="content-card-info-cell"><span>${esc(label)}</span><strong>${esc(value===undefined||value===null||value===''?'—':value)}</strong></div>`;
    function details(p,d=null){const status=p.pdfScheduled===true?'PDF 已安排':'自由探索';let cells=[],emphasisLabel='',emphasisValue='';if(p.type==='night'){cells=[['建議時段',p.time],['停留時間',p.duration],['熱鬧程度',p.crowd?stars(p.crowd):'—'],['適合',p.suitable]];emphasisLabel='⌂ 飯店距離';emphasisValue=hotelDistanceCardValue(p,d);}else if(p.type==='food'){cells=[['口味',p.taste],['適合',p.meal],['建議停留',p.duration],['安排',status]];emphasisLabel=p.priority==='必吃'?'旅程優先級':'料理形式';emphasisValue=p.priority==='必吃'?'🔥 必吃 · 優先安排':'料理推薦 · 非指定餐廳';}else if(p.type==='shopping'){cells=[['購物分類',p.group],['選購時間',p.duration],['類型',p.marketKind||'在地選購'],['安排',status]];emphasisLabel=p.priority==='必買'?'旅程優先級':'選購建議';emphasisValue=p.priority==='必買'?'🛍 必買 · 優先選購':(p.group||'自由選購');}else if(p.type==='photo'){cells=[['行程',Array.isArray(p.days)?p.days.map(x=>'Day '+x).join(' / '):'—'],['停留時間',p.duration],['光線／時段',p.bestTime],['取景',p.drama?'《去有風的地方》':'沿途旅拍']];emphasisLabel='拍攝提示';emphasisValue='完整構圖與拍攝建議請點開查看';}else{cells=[['城市',p.city],['停留時間',p.duration],['類型',category(p).name],['安排',status]];emphasisLabel='完整資訊';emphasisValue='地址、交通與來源請點開查看';}return `<div class="content-card-details"><div class="content-card-info-grid">${cells.map(([l,v])=>cell(l,v)).join('')}</div><div class="content-card-emphasis"><span>${esc(emphasisLabel)}</span><strong>${esc(emphasisValue||'—')}</strong></div></div>`;}
    const actions=p=>`<div class="content-card-footer"><div class="content-card-actions content-card-actions--${p.type==='night'?'2':'3'}"><button class="action" data-focus="${esc(p.id)}">◎ 地圖看位置</button><a class="action" ${navigation.attrs(p)}>↗ <span data-nav-label>${esc(navigation.name(navigation.get()))}導航</span></a>${p.type==='night'?'':`<button class="action" data-copy="${esc(p.id)}">${p.addressVerified?'複製地址':'複製地址／搜尋詞'}</button>`}</div></div>`;
    function contentCard(p,d,{readerKind=''}={}){const priority=p.priority==='必吃'?'🔥 必吃':p.priority==='必買'?'🛍 必買':'';const rating=p.rating?`${priority?priority+' · ':''}${stars(p.rating)} · 網路推薦`:(priority||'尚無評分');return `<article class="content-card content-card--${variant(p)} content-openable" data-item="${esc(p.id)}"${d?.day?` data-reader-day="${d.day}"`:''}${readerKind?` data-reader-kind="${esc(readerKind)}"`:''} title="點一下查看完整內容">${photoSystem.cardFigure(p.photoId,'content-card-media',photoSystem.badgeFor(p))}<div class="content-card-body"><header class="content-card-head"><div class="content-card-heading"><span class="badge">${category(p).symbol} ${esc(p.city)} · ${category(p).name}</span><h3>${esc(p.name)}</h3><span class="content-card-rating">${rating}</span></div>${saveButton(p)}</header><p class="content-card-summary">${esc(p.description)}</p>${details(p,d)}${actions(p)}</div></article>`;}
    function storyReadMinutes(s){const chars=`${s.intro||''}${s.body||''}${s.look||''}`.replace(/\s+/g,'').length;return Math.max(1,Math.ceil(chars/260));}
    function contentStoryCard(s){const days=Array.isArray(s.days)?s.days.map(d=>'Day '+d).join(' / '):'—',cells=[['時期',s.period],['行程',days],['類型',s.kind],['閱讀',`約 ${storyReadMinutes(s)} 分鐘`]];return `<article class="content-card content-card--story" id="story-${esc(s.id)}" data-culture-story="${esc(s.id)}" role="button" tabindex="0" aria-label="閱讀故事：${esc(s.title)}">${photoSystem.cardFigure(s.photoId,'content-card-media',photoSystem.badgeFor(s))}<div class="content-card-body"><header class="content-card-head"><div class="content-card-heading"><span class="badge">${esc(s.city)} · ${esc(s.kind)}</span><h3>${esc(s.title)}</h3><span class="content-card-rating">${esc(s.period)}</span></div></header><p class="content-card-summary">${esc(s.intro)}</p><div class="content-card-details"><div class="content-card-info-grid">${cells.map(([l,v])=>cell(l,v)).join('')}</div><div class="content-card-emphasis"><span>旅途閱讀</span><strong>完整故事與旅途觀察請點開查看</strong></div></div><div class="content-card-footer"><button type="button" class="content-card-read" data-story="${esc(s.id)}" aria-label="閱讀完整故事：${esc(s.title)}">閱讀完整故事 →</button></div></div></article>`;}
    function dayCulture(d){const stories=tripData.culture.filter(st=>Array.isArray(st.days)&&st.days.includes(d.day));if(!stories.length)return '';return `<section class="day-culture" aria-label="Day ${d.day} 風俗與故事"><div class="day-culture-head"><div><span class="eyebrow">STORIES ALONG THE WAY</span><h3>風俗與故事</h3></div><span class="day-culture-count">${stories.length} 篇</span></div><div class="day-story-strip">${stories.map(st=>`<button type="button" class="day-story-card compact-card compact-card--story" data-content-reader-story="${esc(st.id)}" data-reader-day="${d.day}" aria-label="閱讀完整故事：${esc(st.title)}">${photoSystem.storyThumb(st.photoId,photoSystem.badgeFor(st))}<span class="day-story-copy"><small>${esc(st.city)} · ${esc(st.kind)} · ${esc(st.period)}</small><strong>${esc(st.title)}</strong><em>閱讀完整故事 →</em></span></button>`).join('')}</div><div class="day-culture-actions"><button type="button" class="day-culture-library" data-view="culture">查看全部風俗與故事 →</button></div></section>`;}
    function renderNight(){const select=$('#night-day');if(select)select.value=String(nightDay);const content=$('#night-content');if(!content)return;const hotelPanel=d=>getJourney()?.hotelPanel(d)||'';if(String(nightDay)==='all'){const groups=tripData.days.map(d=>{const cards=d.nightRecommendations.map(id=>items[id]).filter(Boolean);if(!cards.length)return '';return `<section class="night-day-group"><div class="night-day-group-head"><div><span class="eyebrow">DAY ${String(d.day).padStart(2,'0')} · ${esc(d.date.slice(5).replace('-','/'))}</span><h3>${esc(d.city)} · 今晚住宿附近</h3></div><button type="button" class="action" data-night-date="${d.day}">只看這晚 →</button></div><div class="content-grid rail rail--content rail--snap">${cards.map(p=>contentCard(p,d)).join('')}</div></section>`;}).filter(Boolean).join('');content.innerHTML=`<div class="note">八天夜間提案總覽。住宿附近步行優先；需要打車時，以高德當晚顯示 20 分鐘內為原則。</div>${groups||'<div class="empty"><h3>目前沒有夜間提案</h3></div>'}`;}else{const d=tripData.days.find(d=>d.day===Number(nightDay));if(!d)return;content.innerHTML=`${hotelPanel(d)}<div class="note">今晚以住宿地點為中心，優先安排步行或短程打車可到的活動，尤其是夜景、夜市與在地文化；打車以高德當晚顯示 20 分鐘內為原則。${esc(d.note)}</div>${d.nightRecommendations.length?`<div class="content-grid rail rail--content rail--snap">${d.nightRecommendations.map(id=>contentCard(items[id],d)).join('')}</div>`:`<div class="empty"><h3>${[1,8].includes(d.day)?'今晚以休息／返程為主':'這晚先不安排住宿附近夜遊'}</h3><p>${esc(tripData.walkNotes[d.day]||'沒有額外夜遊安排。')}</p></div>`}${d.nightCandidates.length?`<details class="walk-pending"><summary>其他住宿附近候選</summary><p>${d.nightCandidates.filter(id=>!d.nightRecommendations.includes(id)).map(id=>esc(items[id].name)).join('、')||'無'}</p><p>這些沒有列入今晚優先順序；若高德當晚顯示 20 分鐘內且體力允許，仍可臨時加入。</p></details>`:''}`;}syncNightDate(false);markRendered?.('night');navigation.sync();}
    function renderFood(){$('#food-filters').innerHTML=['all',...tripData.cities].map(c=>`<button data-city="${c}" class="${c===foodCity?'active':''}" aria-pressed="${c===foodCity}">${c==='all'?'全部城市':c}</button>`).join('');const list=tripData.foods.filter(p=>foodCity==='all'||p.city===foodCity).map((p,i)=>({p,i})).sort((a,b)=>(b.p.priority==='必吃')-(a.p.priority==='必吃')||a.i-b.i).map(x=>x.p);$('#food-list').innerHTML=list.map(p=>contentCard(p)).join('');markRendered?.('food');navigation.sync();}
    function renderShopping(){$('#shopping-content').innerHTML=`<div class="note warm">${esc(tripData.customsNotice)} <a href="${tripData.customsUrl}" target="_blank" rel="noopener noreferrer">查詢官方規定 ↗</a><br><span class="small">🛍「必買」是本次路線的優先伴手禮；「可以買」是次順位。兩者都不代表保證可攜帶入境，仍須檢查成分、產地、包裝與官方規定。</span></div>${['必買','可以買','建議當地吃'].map(group=>`<h3 class="subheading">${group}</h3><div class="content-grid rail rail--content rail--snap">${tripData.shopping.filter(p=>p.group===group).map(p=>contentCard(p)).join('')}</div>`).join('')}`;markRendered?.('shopping');navigation.sync();}
    function renderFavorites(){$('#favorite-list').innerHTML=favoritesStore.size()?favoritesStore.values().map(id=>contentCard(items[id],tripData.days.find(d=>d.day===Number(nightDay)),{readerKind:'favorites'})).join(''):'<div class="empty"><div class="big">♡</div><h3>下一個喜歡的地方，留在這裡。</h3><p>點一下景點、美食或伴手禮旁的愛心，就能隨時找回。</p><button class="primary" data-view="itinerary">去看看行程</button></div>';markRendered?.('favorites');navigation.sync();}
    function renderPhotos(){document.querySelectorAll('[data-photo-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.photoFilter===photoFilter);b.setAttribute('aria-pressed',String(b.dataset.photoFilter===photoFilter));});$('#photo-list').innerHTML=tripData.photoSpots.filter(p=>photoFilter==='all'||p.drama).map(p=>contentCard(p,null,{readerKind:'photo'})).join('');markRendered?.('photos');navigation.sync();}
    function renderCulture(){const filters=[['all','全部故事'],['odd','鄉野奇談'],['republic','民國時期'],['custom','風俗與禮節'],['tales','文學與傳說']];$('#culture-filters').innerHTML=filters.map(([id,label])=>`<button data-culture-filter="${id}" class="${id===cultureFilter?'active':''}" aria-pressed="${id===cultureFilter}">${label}</button>`).join('');const stories=tripData.culture.filter(s=>cultureFilter==='all'||cultureFilter==='republic'&&s.republic||cultureFilter==='odd'&&s.kind==='鄉野奇談'||cultureFilter==='custom'&&['習俗','文化','禮節'].includes(s.kind)||cultureFilter==='tales'&&['文學','傳說'].includes(s.kind));$('#culture-list').innerHTML=stories.map(contentStoryCard).join('');$('#photo-sources').innerHTML=Object.values(tripData.photos).map(p=>{const title=p.source?`<a href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">${esc(p.alt)}</a>`:esc(p.alt),license=p.licenseUrl?`<a href="${esc(p.licenseUrl)}" target="_blank" rel="noopener noreferrer">${esc(p.license)}</a>`:esc(p.license||'');return `<p>${title} — ${esc(p.author)}${license?` · ${license}`:''}。${esc(p.changes)}</p>`;}).join('');markRendered?.('culture');}
    function syncSaved(){document.querySelectorAll('[data-save]').forEach(b=>{const p=items[b.dataset.save];if(!p)return;const saved=favoritesStore.has(p.id);b.setAttribute('aria-pressed',String(saved));b.setAttribute('aria-label',(saved?'取消收藏':'收藏')+p.name);b.textContent=saved?'♥':'♡';});document.querySelectorAll('.fav-count').forEach(el=>el.textContent=favoritesStore.size());}
    const dateValues=()=>['all',...tripData.days.map(d=>String(d.day))];
    function setNightDayState(value){value=String(value);if(!dateValues().includes(value))return false;nightDay=value==='all'?'all':Number(value);const select=$('#night-day');if(select)select.value=value;syncNightDate(false);return true;}
    function syncNightDate(center=false,behavior='auto'){dateRail.sync('#night-date-rail',center,behavior);}
    function stepNightDate(direction){const values=dateValues(),current=String(nightDay);let index=Math.max(0,values.indexOf(current));index=Math.max(0,Math.min(values.length-1,index+direction));setSharedDay?.(values[index],{source:'library',center:true,behavior:'smooth'});}
    function buildDate(){dateRail.build({railSelector:'#night-date-rail',key:'nightDate',navKey:'nightDateNav',allSmall:'全部夜晚',getValue:()=>String(nightDay),setValue:(value,opts)=>setSharedDay?.(value,{source:'library',...opts}),step:stepNightDate});}
    function handleAction(b){if(b.dataset.photoFilter){photoFilter=b.dataset.photoFilter;renderPhotos();return true;}if(b.dataset.cultureFilter){cultureFilter=b.dataset.cultureFilter;renderCulture();return true;}if(b.dataset.story){getReader()?.openStory(b.dataset.story,{day:b.dataset.storyDay,opener:b});return true;}if(b.dataset.nightDay){setSharedDay?.(b.dataset.nightDay,{source:'library',center:true,behavior:'smooth'});showView('night');return true;}if(b.dataset.nightDate){setSharedDay?.(b.dataset.nightDate,{source:'library',center:true,behavior:'smooth'});return true;}if(b.dataset.city){foodCity=b.dataset.city;renderFood();return true;}if(b.dataset.foodId){const dayEl=b.closest('.day-card'),day=dayEl?Number(dayEl.id.replace('day-','')):null;getReader()?.openItem(b.dataset.foodId,{day,kind:'food',opener:b});return true;}return false;}
    function init(){buildDate();}
    return {init,contentCard,contentStoryCard,dayCulture,storyReadMinutes,renderNight,renderFood,renderShopping,renderFavorites,renderPhotos,renderCulture,syncSaved,handleAction,setNightDayState,syncNightDate,getNightDay:()=>nightDay,getFoodCity:()=>foodCity,getPhotoFilter:()=>photoFilter};
  }
  window.YunnanLibrarySystem={create};
})();
