/* Explore Map domain: Leaflet, map rail, date state, geolocation, map detail and gestures. */
(() => {
  'use strict';

  function bindCardInteraction(mapStrip,{openDetail,activate}){
    if(!mapStrip||mapStrip.dataset.mapCardInteractionReady==='1')return;mapStrip.dataset.mapCardInteractionReady='1';
    const HOLD_MS=520,VISUAL_MS=180,TOUCH_MOVE_CANCEL=12,MOUSE_MOVE_CANCEL=8;let gesture=null,visualTimer=0,holdTimer=0,suppressClickUntil=0;
    const clearTimers=()=>{if(visualTimer){clearTimeout(visualTimer);visualTimer=0;}if(holdTimer){clearTimeout(holdTimer);holdTimer=0;}};
    const clearVisual=card=>{card?.classList.remove('long-pressing','long-press-ready');card?.style.removeProperty('--map-hold-remaining');};
    const resetGesture=()=>{clearTimers();if(gesture?.card)clearVisual(gesture.card);gesture=null;};
    const movedTooFar=(event,g)=>Math.hypot(event.clientX-g.startX,event.clientY-g.startY)>(g.pointerType==='mouse'?MOUSE_MOVE_CANCEL:TOUCH_MOVE_CANCEL);
    mapStrip.addEventListener('pointerdown',event=>{const pointerType=event.pointerType||'mouse';if(event.isPrimary===false||(pointerType==='mouse'&&event.button!==0))return;const card=event.target.closest?.('[data-map-strip]');if(!card||!mapStrip.contains(card))return;resetGesture();gesture={pointerId:event.pointerId,pointerType,card,startX:event.clientX,startY:event.clientY,armed:false};visualTimer=setTimeout(()=>{if(!gesture||gesture.pointerId!==event.pointerId||gesture.armed)return;gesture.card.style.setProperty('--map-hold-remaining',`${HOLD_MS-VISUAL_MS}ms`);gesture.card.classList.add('long-pressing');},VISUAL_MS);holdTimer=setTimeout(()=>{if(!gesture||gesture.pointerId!==event.pointerId)return;gesture.armed=true;clearVisual(gesture.card);gesture.card.classList.add('long-press-ready');if(pointerType!=='mouse'&&navigator.vibrate){try{navigator.vibrate(22);}catch{}}},HOLD_MS);},{passive:true});
    mapStrip.addEventListener('pointermove',event=>{if(gesture&&event.pointerId===gesture.pointerId&&movedTooFar(event,gesture))resetGesture();},{passive:true});mapStrip.addEventListener('pointercancel',event=>{if(gesture&&event.pointerId===gesture.pointerId)resetGesture();},{passive:true});
    mapStrip.addEventListener('pointerup',event=>{if(!gesture||event.pointerId!==gesture.pointerId)return;const g=gesture,currentCard=event.target.closest?.('[data-map-strip]'),longPressed=g.armed&&currentCard===g.card;resetGesture();if(!longPressed)return;suppressClickUntil=performance.now()+450;openDetail?.(g.card.dataset.mapStrip,g.card);},{passive:true});
    mapStrip.addEventListener('click',event=>{const card=event.target.closest?.('[data-map-strip]');if(!card||!mapStrip.contains(card))return;if(performance.now()<suppressClickUntil){suppressClickUntil=0;event.preventDefault();event.stopPropagation();return;}event.stopPropagation();activate?.(card.dataset.mapStrip);});
    mapStrip.addEventListener('keydown',event=>{if(!['Enter',' '].includes(event.key))return;const card=event.target.closest?.('[data-map-strip]');if(!card||!mapStrip.contains(card))return;event.preventDefault();event.stopPropagation();activate?.(card.dataset.mapStrip);});
  }

  function create(config){
    const {$,tripData,items,esc,photoSystem,travelUtils,favoritesStore,navigation,readerInteraction,dateRail,bindHorizontalScroller,toast,showView,setSharedDay,toggleFavorite,markRendered,weatherSystem,networkProfile}=config;
    const {category,hasCoords,stars,hotelGradeLabel,iconSvg,placeHours,detailValue,hotelDistanceValue}=travelUtils;
    const customMapStorageKey='yunnan-2026-custom-map-v1',customMapSnowMigrationKey='yunnan-2026-custom-map-snow-migration-v1';
    let customMapPlaces=new Set(),storageAvailable=true,map=null,baseLayer=null,layer=null,markers=new Map(),markerGroups=new Map(),selectedMapId=null,selectedMarkerId=null,mapFilters=new Set(),activeMapTab='scheduled',offlineKnown=[];
    let userLocationPoint=null,watchId=null,userMarker=null,accuracyCircle=null,selectedCircle=null,nearbyOrigin=null,mapDetailReturnState=null;
    try{const raw=localStorage.getItem(customMapStorageKey),saved=raw===null?(Array.isArray(tripData.customMapDefault)?tripData.customMapDefault:[]):JSON.parse(raw||'[]');if(Array.isArray(saved))customMapPlaces=new Set(saved.filter(id=>typeof id==='string'&&items[id]));const seedSnow=Array.isArray(tripData.customMapDefault)&&tripData.customMapDefault.includes('snow')&&items.snow;if(seedSnow&&!localStorage.getItem(customMapSnowMigrationKey)){if(raw!==null){customMapPlaces.add('snow');localStorage.setItem(customMapStorageKey,JSON.stringify([...customMapPlaces]));}localStorage.setItem(customMapSnowMigrationKey,'1');}}catch{storageAvailable=false;}
    const filterIsAll=()=>mapFilters.size===0,filterMatches=p=>filterIsAll()||mapFilters.has(p.type);function resetFilters(){mapFilters.clear();}function toggleFilter(type){if(type==='all'){resetFilters();return;}if(mapFilters.has(type))mapFilters.delete(type);else mapFilters.add(type);if(mapFilters.size===0)resetFilters();}
    const saveButton=p=>`<button class="save-btn" data-save="${esc(p.id)}" aria-pressed="${favoritesStore.has(p.id)}" aria-label="${favoritesStore.has(p.id)?'取消收藏':'收藏'}${esc(p.name)}">${favoritesStore.has(p.id)?'♥':'♡'}</button>`;
    const actions=(p,includeSave=false)=>`<div class="actions"><button class="action" data-focus="${esc(p.id)}">◎ 地圖看位置</button><a class="action" ${navigation.attrs(p)}>↗ <span data-nav-label>${esc(navigation.name(navigation.get()))}導航</span></a><button class="action" data-copy="${esc(p.id)}">${p.addressVerified?'複製中文地址':'複製中文地址／搜尋詞'}</button>${includeSave?saveButton(p):''}</div>`;
    function markerIcon(group,selected=false){const p=group[0],cat=category(p),mixed=group.some(x=>x.type!==p.type);return L.divIcon({className:'custom-marker',html:`<div class="map-symbol-marker${selected?' selected':''}" style="--marker-color:${cat.color}" title="${esc(group.map(x=>x.name).join('、'))}"><span class="map-symbol-icon">${mixed?'<span class="map-mixed">＋</span>':iconSvg(p.type)}</span>${group.length>1?`<b class="map-marker-count">${group.length}</b>`:''}</div>`,iconSize:[44,44],iconAnchor:[22,22]});}
    function groupLabel(p){if(p.group)return String(p.group);if(Array.isArray(p.days)&&p.days.length)return p.days.map(d=>`Day ${d}`).join(' · ');const days=tripData.days.filter(d=>[...d.itinerary,...d.nightRecommendations,...(d.nightCandidates||[]),...d.foods,...d.shopping,...(d.hotel?[d.hotel]:[])].includes(p.id)).map(d=>d.day);return days.length?days.map(d=>`Day ${d}`).join(' · '):(customMapPlaces.has(p.id)?'自定義':'未分組');}
    function anchorFor(p){if(hasCoords(p))return p;return items[p.mapPlaceId]||items[tripData.mapAreas[p.city]]||null;}
    function mapLatLng(lat,lng){const pair=networkProfile?.toMapCoords?networkProfile.toMapCoords(lat,lng):[Number(lat),Number(lng)];return L.latLng(pair[0],pair[1]);}
    const mapLatLngFor=p=>mapLatLng(p.lat,p.lng);
    function wgsLatLngFromMap(point){const pair=networkProfile?.fromMapCoords?networkProfile.fromMapCoords(point.lat,point.lng):[point.lat,point.lng];return L.latLng(pair[0],pair[1]);}
    function userDistanceKm(p){if(!userLocationPoint||!window.L)return null;const anchor=anchorFor(p);if(!anchor||!hasCoords(anchor))return null;return userLocationPoint.distanceTo(L.latLng(anchor.lat,anchor.lng))/1000;}
    const distanceMarkup=p=>{const km=userDistanceKm(p);return `<span class="map-strip-distance" data-map-distance="${esc(p.id)}"${km===null?' hidden':''}>${km===null?'':`距離 ${km<1?Math.round(km*1000)+' m':km.toFixed(1)+' km'}`}</span>`;};
    function updateStripDistances(){document.querySelectorAll('[data-map-distance]').forEach(el=>{const p=items[el.dataset.mapDistance],km=p?userDistanceKm(p):null;el.hidden=km===null;if(km!==null)el.textContent=`距離 ${km<1?Math.round(km*1000)+' m':km.toFixed(1)+' km'}`;});}
    function stripCard(p){const cat=category(p),hours=placeHours(p),label=groupLabel(p);return `<article class="map-strip-card compact-card compact-card--map" data-map-strip="${esc(p.id)}" role="button" tabindex="0" aria-pressed="${p.id===selectedMapId?'true':'false'}" aria-label="${esc(p.name)}；點一下查看附近有什麼可玩，長按查看完整內容" title="點一下看附近 · 長按看完整內容"><span class="map-strip-card-top"><span class="map-strip-type" style="--marker-color:${cat.color}"><i>${iconSvg(p.type)}</i>${esc(cat.name)}</span><span class="map-strip-hours">${hours?esc(hours):'&nbsp;'}</span></span>${photoSystem.mapStrip(p.photoId,photoSystem.badgeFor(p))}<span class="map-strip-card-body"><strong>${esc(p.name)}</strong><small class="map-strip-place-meta">${esc(p.city)}${p.type==='hotel'?` · ★ ${esc(hotelGradeLabel(p))}`:''}${p.duration?` · ${esc(p.duration)}`:''}</small><span class="map-strip-bottom-meta"><span class="map-strip-group"><b>GROUP</b> ${esc(label)}</span>${distanceMarkup(p)}</span></span></article>`;}
    function detailDialogContent(p){const cat=category(p),hours=placeHours(p),label=groupLabel(p),photo=photoSystem.mapDetail(p.photoId,photoSystem.badgeFor(p));let extra='';if(p.type==='night')extra+=detailValue('建議時段',p.time)+detailValue('熱鬧程度',p.crowd?stars(p.crowd):'')+detailValue('適合',p.suitable)+detailValue('飯店 → 景點',hotelDistanceValue(p),true)+detailValue('交通',p.transport,true);if(p.type==='food')extra+=detailValue('口味',p.taste)+detailValue('用餐類型',p.meal);if(p.type==='shopping')extra+=detailValue('購物分類',p.group);if(p.type==='photo')extra+=detailValue('怎麼拍',p.shot,true)+detailValue('光線／時段',p.bestTime,true)+(p.drama?detailValue('取景資訊','《去有風的地方》取景相關'):'');if(p.marketKind)extra+=detailValue('類型',p.marketKind,true);const live=userDistanceKm(p),distanceText=live===null?'':(live<1?`${Math.round(live*1000)} m`:`${live.toFixed(1)} km`),sourceLink=p.source?`<a class="map-detail-source" href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">${esc(p.sourceLabel||'資料來源')} ↗</a>`:'';return `<button type="button" class="map-detail-close" data-map-detail-close aria-label="關閉完整內容">×</button>${photo}<div class="map-detail-content"><div class="map-detail-top"><span class="map-strip-type" style="--marker-color:${cat.color}"><i>${iconSvg(p.type)}</i>${esc(cat.name)}</span>${hours?`<span class="map-detail-hours">${esc(hours)}</span>`:''}</div><h2>${esc(p.name)}</h2><p class="map-detail-description">${esc(p.description)}</p><div class="map-detail-grid">${detailValue('城市',p.city)}${detailValue('GROUP',label)}${detailValue('停留時間',p.duration)}${p.type==='hotel'?detailValue('手冊星級',hotelGradeLabel(p)):''}${p.rating?detailValue('推薦度',stars(p.rating)):''}${distanceText?detailValue('目前距離',distanceText):''}${p.pdfScheduled===true?detailValue('行程狀態','PDF 已安排'):''}${extra}${detailValue('地址／搜尋詞',p.address,true)}${detailValue('座標說明',p.coordinateNote,true)}</div>${sourceLink}<div class="map-detail-actions"><a ${navigation.attrs(p)}>↗ <span data-nav-label>${esc(navigation.name(navigation.get()))}導航</span></a><button type="button" data-copy="${esc(p.id)}">複製地址</button></div></div>`;}
    const detailSequence=()=>{const list=activeMapTab==='custom'?customItems():(activeMapTab==='all'?allItems():scheduledItems());return list.filter(Boolean);};
    function ensureDetailDialog(){let dialog=$('#map-detail-dialog');if(dialog)return dialog;document.body.insertAdjacentHTML('beforeend','<dialog id="map-detail-dialog" class="map-detail-dialog" aria-label="地點完整內容"><button type="button" class="map-detail-nav map-detail-prev" data-map-detail-nav="prev" aria-label="上一張完整內容">‹</button><div class="map-detail-shell"></div><button type="button" class="map-detail-nav map-detail-next" data-map-detail-nav="next" aria-label="下一張完整內容">›</button><div class="map-detail-position" aria-live="polite"></div></dialog>');dialog=$('#map-detail-dialog');dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});dialog.addEventListener('close',()=>{const state=mapDetailReturnState;mapDetailReturnState=null;readerInteraction.restoreReturnStateStable(state);});readerInteraction.bindPopupNavigation(dialog,{surfaceSelector:'.map-detail-shell',navigate:navigateDetail});return dialog;}
    function setDetailPlace(id,{direction=''}={}){const p=items[id];if(!p)return false;const dialog=ensureDetailDialog(),shell=dialog.querySelector('.map-detail-shell'),sequence=detailSequence(),index=sequence.findIndex(x=>x.id===id);shell.classList.remove('slide-from-left','slide-from-right');shell.innerHTML=detailDialogContent(p);shell.scrollTop=0;if(direction){void shell.offsetWidth;shell.classList.add(direction==='prev'?'slide-from-left':'slide-from-right');}dialog.dataset.placeId=id;const prev=dialog.querySelector('[data-map-detail-nav="prev"]'),next=dialog.querySelector('[data-map-detail-nav="next"]'),position=dialog.querySelector('.map-detail-position'),valid=index>=0;if(prev)prev.disabled=!valid||index<=0;if(next)next.disabled=!valid||index>=sequence.length-1;if(position)position.textContent=valid?`${index+1} / ${sequence.length} · 左右滑動`:'完整內容';navigation.sync();return true;}
    function navigateDetail(direction){const dialog=$('#map-detail-dialog');if(!dialog?.open)return;const sequence=detailSequence(),index=sequence.findIndex(x=>x.id===dialog.dataset.placeId),next=index+(direction==='prev'?-1:1);if(index<0||next<0||next>=sequence.length)return;setDetailPlace(sequence[next].id,{direction});}
    function openDetail(id,opener=null){const dialog=ensureDetailDialog();if(!setDetailPlace(id))return;if(!dialog.open)mapDetailReturnState=readerInteraction.captureReturnState(opener,{view:$('#view-map'),horizontal:[$('#map-list')]});if(typeof dialog.showModal==='function'){if(!dialog.open)dialog.showModal();}else dialog.setAttribute('open','');}
    function setFeatureHidden(hidden=true){const el=$('#map-feature-card');if(!el)return;el.hidden=Boolean(hidden);el.setAttribute('aria-hidden',String(Boolean(hidden)));}
    function renderFeature(p,group=[p]){const el=$('#map-feature-card');if(!el)return;if(!p){el.innerHTML='';setFeatureHidden(true);return;}const cat=category(p),siblings=group.filter(x=>x.id!==p.id),inCustom=customMapPlaces.has(p.id);el.innerHTML=`<button class="map-card-close" data-map-card-close aria-label="收起地點小卡">×</button>${photoSystem.mapCard(p.photoId,photoSystem.badgeFor(p))}<div class="map-card-body"><div class="map-card-kicker"><span class="map-card-kind" style="--marker-color:${cat.color}">${iconSvg(p.type)} ${esc(p.city)} · ${esc(cat.name)}</span>${saveButton(p)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="map-card-meta"><span>${p.type==='hotel'?`★ ${esc(hotelGradeLabel(p))}`:(p.rating?stars(p.rating)+' · 網路推薦':'既定安排')}</span>${p.duration?`<span>停留 ${esc(p.duration)}</span>`:''}</div>${p.coordinateNote?`<p class="map-card-note">${esc(p.coordinateNote)}</p>`:''}${weatherSystem?.mapPlaceholder(p,$('#map-day')?.value||'all')||''}${siblings.length?`<div class="map-card-siblings"><span>同一座標還有 ${siblings.length} 個提案</span><div class="map-card-sibling-buttons">${group.map(x=>`<button data-map-pick="${esc(x.id)}" class="${x.id===p.id?'active':''}">${esc(x.name)}</button>`).join('')}</div></div>`:''}<div class="map-card-actions"><a class="map-card-primary" ${navigation.attrs(p)}>↗ <span data-nav-label>${esc(navigation.name(navigation.get()))}導航</span></a><button data-map-scroll="${esc(p.id)}">下方卡片 ↓</button><button class="map-custom-toggle ${inCustom?'active':''}" data-map-custom="${esc(p.id)}" aria-pressed="${inCustom}" aria-label="${inCustom?'從自定義移除':'加入自定義'}${esc(p.name)}">${inCustom?'✓ 自定義':'＋ 自定義'}</button></div></div>`;weatherSystem?.hydrate(el);}
    function syncStripSelection(keepVisible=false){const strip=$('#map-list');if(!strip)return;strip.querySelectorAll('[data-map-strip]').forEach(card=>{const active=card.dataset.mapStrip===selectedMapId;card.classList.toggle('active',active);card.setAttribute('aria-pressed',String(active));});if(keepVisible&&selectedMapId){const card=strip.querySelector(`[data-map-strip="${CSS.escape(selectedMapId)}"]`);if(card){const left=card.offsetLeft-(strip.clientWidth-card.offsetWidth)/2;strip.scrollTo({left:Math.max(0,left),behavior:'smooth'});}}}
    function refreshMarkerSelection(){const seen=new Set();markers.forEach(marker=>{if(seen.has(marker))return;seen.add(marker);const group=markerGroups.get(marker)||[],selected=group.some(x=>x.id===selectedMarkerId||x.id===selectedMapId);marker.setIcon(markerIcon(group,selected));marker.setZIndexOffset(selected?1000:0);});}
    function focusMapOnPlace(anchor){if(!map||!hasCoords(anchor))return;const mobile=window.matchMedia('(max-width: 760px)').matches,targetZoom=mobile?15:16,point=mapLatLngFor(anchor);map.stop();map.setView(point,targetZoom,{animate:true});requestAnimationFrame(()=>{const cardVisible=Boolean($('#map-feature-card')&&!$('#map-feature-card').hidden);map.panInside(point,{paddingTopLeft:!mobile&&cardVisible?[390,44]:[44,44],paddingBottomRight:[44,44],animate:true});});}
    function offlineGroupFor(anchor){if(!anchor||!hasCoords(anchor))return [];return offlineKnown.filter(x=>hasCoords(x)&&x.lat===anchor.lat&&x.lng===anchor.lng);}
    function syncOfflineSelection(){document.querySelectorAll('[data-offline-map-pick]').forEach(button=>{const anchor=items[button.dataset.offlineMapPick],group=offlineGroupFor(anchor),active=group.some(x=>x.id===selectedMapId||x.id===selectedMarkerId);button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}
    function haversineKm(a,b){const r=6371,toRad=v=>Number(v)*Math.PI/180,dLat=toRad(Number(b.lat)-Number(a.lat)),dLng=toRad(Number(b.lng)-Number(a.lng)),la1=toRad(a.lat),la2=toRad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)));}
    function showNearbyStatic(anchor,originId=null){if(!anchor||!hasCoords(anchor))return;const origin=originId?items[originId]:null,sameOriginArea=p=>Boolean(origin&&haversineKm(anchor,p)<.001),isOriginAlias=p=>Boolean(origin&&(p.id===origin.id||(p.name===origin.name&&p.lat===origin.lat&&p.lng===origin.lng))),near=Object.values(items).filter(p=>hasCoords(p)&&p.type!=='hotel'&&!isOriginAlias(p)).map(p=>({p,km:haversineKm(anchor,p)})).filter(x=>x.km<=3).sort((a,b)=>a.km-b.km).filter((x,i,all)=>all.findIndex(y=>y.p.name===x.p.name&&y.p.lat===x.p.lat&&y.p.lng===x.p.lng)===i),rows=near.map(({p,km})=>`<button class="nearby-row" data-focus="${esc(p.id)}">${photoSystem.thumbnail(p,'nearby-thumb')}<span class="nearby-copy"><strong>${esc(p.name)}</strong><small>${category(p).name} · ${esc(p.description)}</small></span><span class="nearby-distance">${sameOriginArea(p)?'同區域':km<1?Math.round(km*1000)+' m':km.toFixed(1)+' km'} →</span></button>`).join('');$('#nearby-panel').innerHTML=`<h3>這附近有什麼可玩？</h3><p class="small">離線計算 · 本站已收錄提案 · 直線 3 公里內 ${near.length} 筆。沒有即時商家搜尋或道路導航。</p>${rows||'<p>附近尚無已定位提案，可改選其他地標。</p>'}`;}
    function selectPlace(id,{anchorId=id,nearby=true,pan=false,focus=false}={}){const p=items[id];if(!p)return;selectedMapId=id;selectedMarkerId=anchorId;const marker=markers.get(anchorId)||markers.get(id),anchor=items[anchorId]||p,offlineGroup=offlineGroupFor(anchor),group=markerGroups.get(marker)||(offlineGroup.length?offlineGroup:[p]);renderFeature(p,group.includes(p)?group:[p]);refreshMarkerSelection();syncOfflineSelection();syncStripSelection(true);if(map&&hasCoords(anchor)){if(focus)focusMapOnPlace(anchor);else if(pan)map.panTo(mapLatLngFor(anchor),{animate:true,duration:.35});if(nearby)showNearby(L.latLng(anchor.lat,anchor.lng),false,p.id);}else if(nearby&&hasCoords(anchor))showNearbyStatic(anchor,p.id);}
    const distance=(p,d)=>`飯店 → 景點：${hotelDistanceValue(p,d)}`;
    function normalizedName(name=''){return String(name).replace(/[·・\s（）()\-—／/「」【】]/g,'').replace(/(?:夜遊|夜間|晚上|夜景|散步)$/g,'').trim();}
    function isScheduledDuplicate(p){if(!p)return false;if(p.pdfScheduled===true)return true;const city=String(p.city||'').trim(),name=normalizedName(p.name);if(!name)return false;return Object.values(items).some(s=>{if(!s||s===p||s.pdfScheduled!==true)return false;if(city&&s.city&&String(s.city).trim()!==city)return false;const scheduledName=normalizedName(s.name);return scheduledName&&(name===scheduledName||(Math.min(name.length,scheduledName.length)>=4&&(name.includes(scheduledName)||scheduledName.includes(name))));});}
    function mapItems(){const dayValue=$('#map-day')?.value||'all',ds=dayValue==='all'?tripData.days:tripData.days.filter(d=>String(d.day)===dayValue),ids=new Set(ds.flatMap(d=>[...d.itinerary,...d.nightRecommendations,...(d.nightCandidates||[]),...d.foods,...d.shopping,...(d.hotel?[d.hotel]:[])]));tripData.photoSpots.filter(p=>dayValue==='all'||p.days.includes(Number(dayValue))).forEach(p=>ids.add(p.id));if(dayValue==='all')tripData.shopping.forEach(p=>ids.add(p.id));return [...ids].map(id=>items[id]).filter(filterMatches);}
    const scheduledItems=()=>mapItems().filter(p=>p.pdfScheduled===true);
    function customItems(){const dayValue=$('#map-day')?.value||'all',dayNumber=dayValue==='all'?null:Number(dayValue);return [...customMapPlaces].map(id=>items[id]).filter(Boolean).filter(p=>!isScheduledDuplicate(p)).filter(p=>dayNumber===null||!Array.isArray(p.days)||p.days.includes(dayNumber)).filter(filterMatches);}
    function allItems(){const seen=new Set(),result=[];[...mapItems(),...customItems()].forEach(p=>{if(p&&!seen.has(p.id)){seen.add(p.id);result.push(p);}});return result;}
    function renderTabs(){const tabs=$('#map-strip-tabs');if(!tabs)return;const counts={all:allItems().length,scheduled:scheduledItems().length,custom:customItems().length};tabs.innerHTML=`<button type="button" role="tab" data-map-tab="all" aria-selected="${activeMapTab==='all'}" class="${activeMapTab==='all'?'active':''}">全部 <b>${counts.all}</b></button><button type="button" role="tab" data-map-tab="scheduled" aria-selected="${activeMapTab==='scheduled'}" class="${activeMapTab==='scheduled'?'active':''}">已安排 <b>${counts.scheduled}</b></button><button type="button" role="tab" data-map-tab="custom" aria-selected="${activeMapTab==='custom'}" class="${activeMapTab==='custom'?'active':''}">自定義 <b>${counts.custom}</b></button>`;}
    function renderStrip(){const strip=$('#map-list');if(!strip)return;renderTabs();const ps=activeMapTab==='custom'?customItems():(activeMapTab==='all'?allItems():scheduledItems());strip.innerHTML=ps.length?ps.map(stripCard).join(''):(activeMapTab==='custom'?'<div class="map-strip-empty"><h3>還沒有自定義地點</h3><p>點地圖座標，再從左側小卡按「＋ 自定義」。</p></div>':'<div class="map-strip-empty"><h3>這一天沒有此類項目</h3><p>試試其他日期或「全部」。</p></div>');syncStripSelection(false);updateStripDistances();}
    function toggleCustom(id){const p=items[id];if(!p)return;if(customMapPlaces.has(id))customMapPlaces.delete(id);else customMapPlaces.add(id);try{localStorage.setItem(customMapStorageKey,JSON.stringify([...customMapPlaces]));storageAvailable=true;}catch{storageAvailable=false;}const marker=markers.get(selectedMarkerId)||markers.get(id),group=markerGroups.get(marker)||[p];if(selectedMapId===id)renderFeature(p,group.includes(p)?group:[p]);renderStrip();toast(storageAvailable?(customMapPlaces.has(id)?'已加入自定義地點':'已從自定義移除'):'無法寫入瀏覽器儲存空間；自定義僅保留至本頁關閉');}
    function popup(p){const d=tripData.days.find(x=>String(x.day)===$('#map-day')?.value);return `<h3>${esc(p.name)}</h3><p>${category(p).name} · ${p.type==='hotel'?`★ ${esc(hotelGradeLabel(p))}`:stars(p.rating)}<br>停留：${esc(p.duration)}</p><p>${esc(p.description)}</p><p class="small">${esc(p.coordinateNote)}<br>${d?esc(distance(p,d)):'選擇日期以查看與當晚飯店的距離'}</p>${actions(p,true)}`;}
    function resolveOverlaps(){if(!map||!window.L||!markerGroups.size)return;const entries=[];markerGroups.forEach((group,marker)=>{const p=group?.[0];if(!p||!hasCoords(p))return;const trueLatLng=mapLatLngFor(p);marker.setLatLng(trueLatLng);entries.push({marker,trueLatLng,point:map.latLngToContainerPoint(trueLatLng)});});if(entries.length<2)return;const threshold=46,visited=new Set();for(let i=0;i<entries.length;i++){if(visited.has(i))continue;const cluster=[],queue=[i];visited.add(i);while(queue.length){const a=queue.shift();cluster.push(a);for(let j=0;j<entries.length;j++){if(visited.has(j))continue;const dx=entries[a].point.x-entries[j].point.x,dy=entries[a].point.y-entries[j].point.y;if(Math.hypot(dx,dy)<threshold){visited.add(j);queue.push(j);}}}if(cluster.length<2)continue;const cx=cluster.reduce((sum,k)=>sum+entries[k].point.x,0)/cluster.length,cy=cluster.reduce((sum,k)=>sum+entries[k].point.y,0)/cluster.length,radius=Math.min(34,24+cluster.length*2);cluster.forEach((k,pos)=>{const angle=-Math.PI/2+(Math.PI*2*pos/cluster.length),pt=L.point(cx+Math.cos(angle)*radius,cy+Math.sin(angle)*radius);entries[k].marker.setLatLng(map.containerPointToLatLng(pt));});}}
    function fitVisible(places){if(!map||!window.L)return;const unique=[],seen=new Set();places.filter(hasCoords).forEach(p=>{const key=`${Number(p.lat).toFixed(6)},${Number(p.lng).toFixed(6)}`;if(!seen.has(key)){seen.add(key);unique.push(mapLatLngFor(p));}});if(!unique.length)return;const desktop=window.matchMedia('(min-width: 761px)').matches,cardVisible=Boolean($('#map-feature-card')&&!$('#map-feature-card').hidden);map.stop();map.invalidateSize({pan:false});map.fitBounds(L.latLngBounds(unique),{paddingTopLeft:desktop&&cardVisible?[390,52]:[44,44],paddingBottomRight:desktop?[52,52]:[44,44],maxZoom:14,animate:false});}
    function renderOfflineMap(known,reason='offline'){
      if(map){try{map.remove();}catch{}map=null;baseLayer=null;layer=null;markers.clear();markerGroups.clear();}
      offlineKnown=known.slice();const root=$('#map');if(!root)return;
      if(!known.length){root.innerHTML='<div class="empty"><h3>目前沒有可定位地標</h3><p>可切換其他日期或分類。</p></div>';renderFeature(null);return;}
      const lats=known.map(p=>Number(p.lat)),lngs=known.map(p=>Number(p.lng)),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLng=Math.min(...lngs),maxLng=Math.max(...lngs),latSpan=Math.max(.02,maxLat-minLat),lngSpan=Math.max(.02,maxLng-minLng),pad=.08;
      const groups=new Map();known.forEach(p=>{const key=`${p.lat},${p.lng}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);});
      if(!selectedMapId||!known.some(p=>p.id===selectedMapId))selectedMapId=known[0].id;if(!selectedMarkerId||!known.some(p=>p.id===selectedMarkerId))selectedMarkerId=selectedMapId;
      const buttons=[...groups.values()].map(group=>{const p=group[0],x=pad+(1-pad*2)*(Number(p.lng)-minLng)/lngSpan,y=1-(pad+(1-pad*2)*(Number(p.lat)-minLat)/latSpan),cat=category(p),active=group.some(x=>x.id===selectedMapId||x.id===selectedMarkerId);return `<button type="button" class="offline-map-marker ${active?'active':''}" style="left:${(x*100).toFixed(2)}%;top:${(y*100).toFixed(2)}%;--marker-color:${cat.color}" data-offline-map-pick="${esc(p.id)}" aria-pressed="${active}" title="${esc(group.map(x=>x.name).join('、'))}"><i>${iconSvg(p.type)}</i>${group.length>1?`<b>${group.length}</b>`:''}</button>`;}).join('');
      const mode=reason==='offline'?'目前離線':'線上底圖程式暫時不可用';root.innerHTML=`<div class="offline-map-shell"><div class="offline-map-caption"><strong>雲南離線簡圖</strong><span>${mode} · 地標位置依本站座標比例顯示</span></div><div class="offline-map-canvas" role="group" aria-label="雲南旅程離線地標簡圖"><span class="offline-map-north">N ↑</span><span class="offline-map-watermark">YUNNAN</span>${buttons}</div><div class="offline-map-legend">可點地標查看卡片與離線 3 公里附近提案；此簡圖不是道路導航底圖。</div></div>`;
      const selected=items[selectedMapId];if(selected){const anchor=items[selectedMarkerId]||selected,group=offlineGroupFor(anchor);renderFeature(selected,group.length?group:[selected]);}else renderFeature(null);syncOfflineSelection();syncStripSelection(false);navigation.sync();
    }
    function applyBaseLayer(){
      if(!map||!window.L)return;
      if(baseLayer){try{map.removeLayer(baseLayer);}catch{}baseLayer=null;}
      const config=networkProfile?.tileConfig?.()||{label:'OpenStreetMap',url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',options:{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}};
      baseLayer=L.tileLayer(config.url,config.options||{}).on('tileerror',()=>{const status=$('#map-status');if(status)status.textContent=`${config.label} 底圖連線不穩；標記與下方清單仍可使用。`;}).addTo(map);
      baseLayer.bringToBack?.();
    }
    function render(fitView=true){
      syncDate(false);
      $('#map-filters').innerHTML=['all','itinerary','hotel','night','food','shopping','photo'].map(type=>{const active=type==='all'?filterIsAll():mapFilters.has(type);return `<button data-filter="${type}" class="${active?'active':''}" aria-pressed="${active}">${type==='all'?'<span class="filter-map-icon">⌖</span>全部':`<span class="filter-map-icon" style="--marker-color:${tripData.categories[type].color}">${iconSvg(type)}</span>${tripData.categories[type].name}`}</button>`;}).join('');
      const ps=mapItems(),known=ps.filter(hasCoords),nonPoint=ps.length-known.length,profileName=networkProfile?.name?.(networkProfile.get?.())||'國際版';
      $('#map-status').textContent=`${profileName} · ${ps.length} 筆行程內容 · ${known.length} 筆可定位地標${nonPoint?` · ${nonPoint} 筆為交通／品項／未指定場館等非獨立地標`:''}`;
      renderStrip();markRendered?.('map');
      if(!navigator.onLine||!window.L){renderOfflineMap(known,!navigator.onLine?'offline':'library');$('#map-status').textContent+=` · ${!navigator.onLine?'目前離線，顯示地標簡圖':'地圖程式暫時不可用，顯示地標簡圖'}`;return;}
      offlineKnown=[];
      if(!map){
        $('#map').innerHTML='';
        map=L.map('map',{scrollWheelZoom:false,zoomControl:false}).setView(mapLatLng(26.25,101.1),7);
        const LocateControl=L.Control.extend({options:{position:'bottomright'},onAdd(){const wrap=L.DomUtil.create('div','leaflet-bar leaflet-control map-locate-control'),button=L.DomUtil.create('button','map-locate-button',wrap);button.type='button';button.title='定位到我的位置';button.setAttribute('aria-label','定位到我的位置');button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';L.DomEvent.disableClickPropagation(wrap);L.DomEvent.disableScrollPropagation(wrap);L.DomEvent.on(button,'click',e=>{L.DomEvent.stop(e);if(watchId!==null&&userLocationPoint){map.stop();map.setView(mapLatLng(userLocationPoint.lat,userLocationPoint.lng),Math.max(map.getZoom(),15),{animate:false});}else startLocation();});return wrap;}});
        new LocateControl().addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);applyBaseLayer();map.createPane('userLocation').style.zIndex=625;layer=L.layerGroup().addTo(map);map.on('click',e=>showNearby(wgsLatLngFromMap(e.latlng),true));map.on('zoomend',()=>requestAnimationFrame(resolveOverlaps));
      }
      layer.clearLayers();markers.clear();markerGroups.clear();
      const groups=new Map();known.forEach(p=>{const key=`${p.lat},${p.lng}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);});
      const visibleIds=new Set(ps.map(p=>p.id));if(!selectedMapId||!visibleIds.has(selectedMapId))selectedMapId=known[0]?.id||null;if(!selectedMarkerId||!visibleIds.has(selectedMarkerId))selectedMarkerId=selectedMapId;
      groups.forEach(group=>{const p=group[0],selected=group.some(x=>x.id===selectedMarkerId||x.id===selectedMapId),marker=L.marker(mapLatLngFor(p),{title:group.map(x=>x.name).join('、'),icon:markerIcon(group,selected),riseOnHover:true}).addTo(layer);markerGroups.set(marker,group);group.forEach(x=>markers.set(x.id,marker));marker.on('click',()=>{setFeatureHidden(false);const current=group.find(x=>x.id===selectedMapId),target=current||group[0];selectPlace(target.id,{anchorId:target.id,nearby:true,pan:false});});});
      requestAnimationFrame(resolveOverlaps);const selected=items[selectedMapId];if(selected){const marker=markers.get(selectedMarkerId)||markers.get(selectedMapId);renderFeature(selected,markerGroups.get(marker)||[selected]);}else renderFeature(null);syncStripSelection(false);map.invalidateSize({pan:false});if(fitView!==false&&known.length)fitVisible(known);requestAnimationFrame(()=>requestAnimationFrame(resolveOverlaps));navigation.sync();
    }
    function showNearby(point,openPopup=false,originId=null){
      if(!map)return;
      nearbyOrigin=point;
      const origin=originId?items[originId]:null;
      const sameCoordinate=(p,q)=>Boolean(p&&q&&hasCoords(p)&&hasCoords(q)&&p.lat===q.lat&&p.lng===q.lng);
      const sameOriginArea=p=>Boolean(origin&&point.distanceTo(L.latLng(p.lat,p.lng))<1);
      const isOriginAlias=p=>Boolean(origin&&(p.id===origin.id||(p.name===origin.name&&sameCoordinate(p,origin))));
      const formatNearbyDistance=({p,km})=>sameOriginArea(p)?'同區域':(km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1)} km`);
      const near=Object.values(items)
        .filter(p=>hasCoords(p)&&p.type!=='hotel'&&!isOriginAlias(p))
        .map(p=>({p,km:point.distanceTo(L.latLng(p.lat,p.lng))/1000}))
        .filter(x=>x.km<=3)
        .sort((a,b)=>a.km-b.km)
        .filter((x,i,all)=>all.findIndex(y=>y.p.name===x.p.name&&y.p.lat===x.p.lat&&y.p.lng===x.p.lng)===i);
      const rows=near.map(item=>{const {p}=item;return `<button class="nearby-row" data-focus="${esc(p.id)}">${photoSystem.thumbnail(p,'nearby-thumb')}<span class="nearby-copy"><strong>${esc(p.name)}</strong><small>${category(p).name} · ${esc(p.description)}</small></span><span class="nearby-distance">${formatNearbyDistance(item)} →</span></button>`;}).join('');
      $('#nearby-panel').innerHTML=`<h3>這附近有什麼可玩？</h3><p class="small">全部八天 · 本站已收錄提案 · 直線 3 公里內 ${near.length} 筆。共用地區參考座標顯示「同區域」；其他距離為直線參考，非步行路線／即時商家搜尋。</p>${rows||'<p>附近尚無已定位的景點，試試點選其他標記；下方仍可按名稱導航。</p>'}`;
      if(selectedCircle)selectedCircle.remove();
      const displayPoint=mapLatLng(point.lat,point.lng);selectedCircle=L.circle(displayPoint,{radius:3000,color:'#bc7945',weight:1,fillOpacity:.035,interactive:false}).addTo(map);
      if(openPopup)L.popup().setLatLng(displayPoint).setContent(`<strong>附近 ${near.length} 筆提案</strong><p>${near.slice(0,4).map(x=>esc(x.p.name)).join('、')||'此處尚無已定位項目'}</p><button class="action" data-nearby>查看附近清單 ↓</button>`).openOn(map);
    }
    function focusPlace(id){const p=items[id];if(!p)return;setSharedDay?.('all',{source:'map',renderMap:false,fitMap:false,center:false});resetFilters();showView('map',false,false);requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!map)render(false);syncDate(true,'smooth');const anchor=anchorFor(p);if(!anchor||!hasCoords(anchor)){renderFeature(p,[p]);toast('尚無可用參考座標，請用卡片的中文名稱導航');return;}if(!map){selectedMapId=p.id;selectedMarkerId=anchor.id;renderFeature(p,offlineGroupFor(anchor).length?offlineGroupFor(anchor):[p]);syncOfflineSelection();syncStripSelection(true);showNearbyStatic(anchor,p.id);$('#map').scrollIntoView({block:'start',behavior:'auto'});return;}map.stop();map.invalidateSize({pan:false});map.setView(mapLatLngFor(anchor),16,{animate:false});selectPlace(p.id,{anchorId:anchor.id,nearby:true,pan:false});$('#map').scrollIntoView({block:'start',behavior:'auto'});}));}
    function stopLocation(message='已停止定位並移除位置標記。'){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(userMarker)userMarker.remove();if(accuracyCircle)accuracyCircle.remove();userMarker=accuracyCircle=null;userLocationPoint=null;updateStripDistances();$('[data-stop-location]').hidden=true;$('#location-status').textContent=message;}
    function startLocation(){if(!map){$('#location-status').textContent='請先連線載入地圖後再試定位。';return;}if(!window.isSecureContext||!navigator.geolocation){$('#location-status').textContent='此瀏覽器環境不支援定位。手機請以 HTTPS 網址開啟，並使用 Safari 或 Chrome 允許位置權限。';return;}stopLocation('正在取得位置，請允許瀏覽器定位…');$('[data-stop-location]').hidden=false;let first=true;watchId=navigator.geolocation.watchPosition(position=>{const {latitude,longitude,accuracy}=position.coords;if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||!Number.isFinite(accuracy))return;userLocationPoint=L.latLng(latitude,longitude);const displayPoint=mapLatLng(latitude,longitude);updateStripDistances();if(!userMarker){userMarker=L.circleMarker(displayPoint,{pane:'userLocation',radius:8,color:'#fff',weight:3,fillColor:'#2375df',fillOpacity:1}).addTo(map).bindPopup('我的位置');accuracyCircle=L.circle(displayPoint,{radius:accuracy,color:'#2375df',weight:1,fillOpacity:.09,interactive:false}).addTo(map);}else{userMarker.setLatLng(displayPoint);accuracyCircle.setLatLng(displayPoint).setRadius(accuracy);}$('#location-status').textContent=`定位中 · 精度約 ±${Math.round(accuracy)} 公尺 · ${new Date(position.timestamp).toLocaleTimeString('zh-TW')} 更新。藍點為裝置位置；不儲存定位紀錄。`;if(first){map.setView(displayPoint,15);showNearby(userLocationPoint);first=false;}},error=>stopLocation(({1:'定位遭拒：請在瀏覽器網站設定允許位置，並確認手機定位服務已開啟；使用 HTTPS 網頁後重試。',2:'暫時無法取得位置，請確認手機定位服務及網路後重試。',3:'定位逾時，請移到訊號較好的地方再按「我的位置」。'})[error.code]||'定位失敗，請重試。'),{enableHighAccuracy:true,timeout:20000,maximumAge:10000});}
    function activateStripCard(id){const p=items[id];if(!p)return;const anchor=anchorFor(p);setFeatureHidden(false);if(!anchor||!hasCoords(anchor)){selectedMapId=p.id;selectedMarkerId=p.id;renderFeature(p,[p]);refreshMarkerSelection();syncStripSelection(true);const panel=$('#nearby-panel');if(panel)panel.innerHTML=`<h3>這附近有什麼可玩？</h3><p class="small">${esc(p.name)} 尚無可用參考座標，因此暫時無法計算 3 公里內提案。</p>`;toast('這張卡片尚無可用參考座標');return;}if(!map){selectedMapId=p.id;selectedMarkerId=anchor.id;const group=offlineGroupFor(anchor);renderFeature(p,group.length?group:[p]);syncOfflineSelection();syncStripSelection(true);showNearbyStatic(anchor,p.id);toast(navigator.onLine?'地圖程式尚未載入，已改用簡圖':'目前離線，已在簡圖選取地標');return;}selectPlace(p.id,{anchorId:anchor.id,nearby:true,focus:true});}
    const dateValues=()=>['all',...tripData.days.map(d=>String(d.day))];
    function syncDate(center=false,behavior='auto'){dateRail.sync('#map-date-rail',center,behavior);}
    function setDayState(value){value=String(value);if(!dateValues().includes(value))return false;const select=$('#map-day');if(select)select.value=value;syncDate(false);return true;}
    function stepDate(direction){const values=dateValues(),current=$('#map-day')?.value||'all';let index=Math.max(0,values.indexOf(current));index=Math.max(0,Math.min(values.length-1,index+direction));setSharedDay?.(values[index],{source:'map',fitMap:true,center:true,behavior:'smooth'});}
    function buildDate(){dateRail.build({railSelector:'#map-date-rail',key:'mapDate',navKey:'mapDateNav',allSmall:'完整旅程',getValue:()=>$('#map-day')?.value||'all',setValue:(value,opts)=>setSharedDay?.(value,{source:'map',fitMap:true,...opts}),step:stepDate});}
    function handleAction(b){if(b.dataset.offlineMapPick){const anchor=items[b.dataset.offlineMapPick];if(anchor){const group=offlineGroupFor(anchor),target=group.find(x=>x.id===selectedMapId)||group[0]||anchor;selectPlace(target.id,{anchorId:anchor.id,nearby:true});}return true;}if(b.hasAttribute('data-nearby')){$('#nearby-panel').scrollIntoView({block:'start'});return true;}if(b.hasAttribute('data-map-card-close')){setFeatureHidden(true);return true;}if(b.dataset.mapTab){activeMapTab=['all','custom','scheduled'].includes(b.dataset.mapTab)?b.dataset.mapTab:'scheduled';renderStrip();return true;}if(b.dataset.mapCustom){toggleCustom(b.dataset.mapCustom);return true;}if(b.dataset.mapStripNav){const strip=$('#map-list'),dir=b.dataset.mapStripNav==='prev'?-1:1;strip?.scrollBy({left:dir*Math.max(260,strip.clientWidth*.72),behavior:'smooth'});return true;}if(b.dataset.mapPick){selectPlace(b.dataset.mapPick,{anchorId:b.dataset.mapPick,nearby:true,pan:true});return true;}if(b.dataset.mapScroll){const strip=$('#map-list');let target=strip?.querySelector(`[data-map-strip="${CSS.escape(b.dataset.mapScroll)}"]`);if(!target&&activeMapTab==='custom'){activeMapTab='scheduled';renderStrip();target=strip?.querySelector(`[data-map-strip="${CSS.escape(b.dataset.mapScroll)}"]`);}if(target&&strip){const left=target.offsetLeft-(strip.clientWidth-target.offsetWidth)/2;strip.scrollTo({left:Math.max(0,left),behavior:'smooth'});document.querySelector('.map-strip-section')?.scrollIntoView({block:'nearest',behavior:'smooth'});}else toast('這個地點目前不在下方清單');return true;}if(b.dataset.focus){focusPlace(b.dataset.focus);return true;}if(b.hasAttribute('data-geolocate')){startLocation();return true;}if(b.hasAttribute('data-stop-location')){stopLocation();return true;}if(b.dataset.mapDay){resetFilters();setSharedDay?.(b.dataset.mapDay,{source:'map',renderMap:false,fitMap:true,center:true,behavior:'smooth'});showView('map',true,true);return true;}if(b.dataset.filter){toggleFilter(b.dataset.filter);render();return true;}if(b.dataset.locate){focusPlace(b.dataset.locate);return true;}if(b.hasAttribute('data-map-detail-close')){$('#map-detail-dialog')?.close();return true;}if(b.dataset.mapDetailNav){navigateDetail(b.dataset.mapDetailNav);return true;}return false;}
    function init(){buildDate();const strip=$('#map-list');bindCardInteraction(strip,{openDetail,activate:activateStripCard});bindHorizontalScroller(strip,{mouseDrag:true,wheel:false});}
    function invalidate(){map?.invalidateSize({pan:false});}
    function cleanup(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);}
    return {init,render,handleAction,focusPlace,groupLabel,placeHours,detailValue,iconSvg,setDayState,syncDate,invalidate,cleanup,isCreated:()=>Boolean(map),isStorageAvailable:()=>storageAvailable};
  }

  window.YunnanMapSystem={create};
})();
